### ISSUE TITLE
Bug v2.0: List Instances - Hidden Attribute Change Exception

### ISSUE THREAD

**Issue by 2P2-Anthony** [SharePoint/PnP-Partner-Pack#155] opened 2016-09-27 06:21 UTC
V 2.0

Updated to v2.0 as per the docs. Re-published all Jobs and the Web Application. Created a new Template using the same Site Collection I was testing with v1.1 (which worked - up to a point - but at least threw now errors after routing around the Composed Looks Bug), and then attempted to make a new Site Collection using the new Template. Ran into the following error:

09/27/2016 06:15:53 > a87042: INFO] 07/11 - List instances
[09/27/2016 06:16:43 > a87042: INFO] Exception occurred: Cannot change Hidden attribute for this field
[09/27/2016 06:16:43 > a87042: INFO] Stack Trace:
[09/27/2016 06:16:43 > a87042: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
[09/27/2016 06:16:43 > a87042: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
[09/27/2016 06:16:43 > a87042: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
[09/27/2016 06:16:43 > a87042: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
[09/27/2016 06:16:43 > a87042: INFO]    at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
[09/27/2016 06:16:43 > a87042: INFO]    at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
[09/27/2016 06:16:43 > a87042: INFO]    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
[09/27/2016 06:16:43 > a87042: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.UpdateFieldRef(List siteList, Guid fieldId, FieldRef fieldRef)
[09/27/2016 06:16:43 > a87042: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
[09/27/2016 06:16:43 > a87042: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
[09/27/2016 06:16:43 > a87042: INFO]    at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
[09/27/2016 06:16:43 > a87042: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.CreateSiteCollection(SiteCollectionProvisioningJob job)
[09/27/2016 06:16:43 > a87042: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.RunJobInternal(ProvisioningJob job)
[09/27/2016 06:16:43 > a87042: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningJobHandler.RunJob(ProvisioningJob job)

Not quite sure where to go from here with this error.

**Comment by PaoloPia** [comment] 2016-09-30 02:41
Hi,
Can you share the XML of the template or at least the (failing) list definition within the template? Thanks.

**Comment by 2P2-Anthony** [comment] 2016-10-03 15:48
Here ya go, I've attached the full P2P file that's loaded into the PnPProvisioningTemplates Library.

[Basic Site Collection v2.zip](https://github.com/OfficeDev/PnP-Partner-Pack/files/506628/Basic.Site.Collection.v2.zip)

**Comment by PaoloPia** [comment] 2017-01-07 12:41
Hi,
Sorry for the delayed answer. I just had a look into the template, but there is something weird. The template includes libraries that should not be there, because they are part of the base template for a Site Collection created as STS#0. Just wondering, are you still experiencing this issue? Have you tried to refresh the template file before creating a new site from there? Thanks.

**Comment by PaoloPia** [comment] 2017-02-24 15:38
Hi,
I will close this item, because you did not provided any answer after about two months. In case of any further need, let me know and I will be more than happy to re-open the issue. Thanks.

**Closed by PaoloPia** 2017-02-24 15:38 UTC

**Comment by RajendhiranMuthusamy** [comment] 2017-06-26 13:05
Hi All,
Creating a document library using the PnP Provisioning i am facing the 
Error occurred at ApplyProvisioningTemplate method: Unable to change the "Hidden" attribute for this field.
I could not identify the root cause of the issue where the exact issue happen.

This is my FieldRef
<pnp:FieldRef ID="e9e0d76a-8fb7-4bf7-8b19-6a2a0c383178" Name="d459f67e04d9415288bb304c1f7a26fd" Hidden="true" DisplayName="CountryRMJurisdiction_0" />
            <pnp:FieldRef ID="2262bb81-3f18-448b-a2bd-72cfa652e17c" Name="n356d7f9e334406abd0d136b463f1540" Hidden="true" DisplayName="SBUBUContentOwner_0" />
            <pnp:FieldRef ID="13377ba9-e17c-4a1a-a617-74ccbfb55017" Name="cf5dfb359dc242639952a3d2295dd84f" Hidden="true" DisplayName="ProjectFileDocument_0" />
            <pnp:FieldRef ID="1390a86a-23da-45f0-8efe-ef36edadfb39" Name="TaxKeywordTaxHTField" Hidden="true" DisplayName="TaxKeywordTaxHTField" />

Please help on this to fix this issue.

Regards,
Rajendhiran M
