### ISSUE TITLE
Problem returning principles on create site collection page.

### ISSUE THREAD

**Issue by leedale1981** [SharePoint/PnP-Partner-Pack#217] opened 2017-01-25 14:47 UTC
I have deployed V2.0 of the PnP Partner Pack and I have confirmed the application is all working except that on the Create Site Collection page I am unable to return any principles from my Azure AD directory.

I can return site collections from the tenant and enable the partner pack on them and the sub site creation is working but on the create site collection page when I type a principle name into the Site collection administrator box it returns nothing and I am subsequently unable to create a site collection.

I have checked that the Azure AD app registration have the correct permissions and I have tried using the full username and the display name but nothing gets returned.

Also if I put in a special character like an ' I get a javascript error pop up. I have attached a screenshot.

![pnp1](https://cloud.githubusercontent.com/assets/3600843/22294964/2482038c-e30d-11e6-83d5-14a6e50b8cc8.png)

Am I missing some configuration or is this a bug? I followed the v2 setup guide on YouTube.

Thanks

**Comment by leedale1981** [comment] 2017-02-02 09:27
OK after a little debugging I found the problem with this. My configuration was correct but I found the Partner Pack application uses the Graph API to return users which end up calling the URL below to filter down the users searched for in the People Picker box 

https://graph.microsoft.com/v1.0/users?$select=DisplayName,UserPrincipalName,Mail&$filter=startswith(DisplayName,'chri') or startswith(UserPrincipalName,'chri') or startswith(Mail,'chri')

This call returns the filtered users fine but the problem comes when the application calls the function MapUsers().  This function has the following loop which checks for a the Mail property of the user and doesn't add them to the returned users if the Mail property is null or empty.

`PrincipalsViewModel result = new PrincipalsViewModel();

            if (source != null)
            {
                foreach (var u in source.Where(us => !String.IsNullOrEmpty(us.Mail)))
                {
                    result.Principals.Add(await MapUser(u));
                }
            }

            return result;`

Now my issue is that my dev tenant doesn't have email addresses assigned to the user accounts and therefore doesn't return any users for this.

I suppose this is by design but I am wondering whether this check for a valid mail address is needed, if it can be removed for people like me that are working in a dev tenant where the users might night have exchange licences?

I am happy to update the code if the consensus is that the check is not needed and submit a pull request. Or if anyone can explain the necessity for this check?

Thanks

**Comment by leedale1981** [comment] 2017-02-02 09:44
Also looking at the user properties in Azure AD vs Office 365 admin I can see that in Azure AD there is an email address set but in Office 365 admin there isn't it says there needs to be an exchange licence assigned to the user to setup mail settings. This could be a problem for dev tenants as we wouldn't want to assign exchange licences to users. Looks like the Graph API returns the O365 mail settings unless I'm missing come email configuration somewhere?
![azuread1](https://cloud.githubusercontent.com/assets/3600843/22544327/32f92920-e92c-11e6-8908-689f5308cee1.png)
![azuread2](https://cloud.githubusercontent.com/assets/3600843/22544328/32f94e6e-e92c-11e6-9c02-826dff2b69e6.png)

**Comment by joelfmrodrigues** [comment] 2017-02-07 10:28
Same here with a dev environment. I could potentially work on a PR to handle this, but not sure what's the proffered approach from the team. Can someone please provide some guidance on whether this is something you would consider for a PR? Maybe something as simple as not resolving the user if not possible?

**Comment by leedale1981** [comment] 2017-02-07 14:45
I think maybe removing the check for a users email in the MapUsers() function could be a solution. I mean is it really necessary to check the user has a email as you may still want to set that user as the site administrator even if they don't have an email.

**Comment by joelfmrodrigues** [comment] 2017-02-07 15:05
@PaoloPia could you please advise?

**Comment by PaoloPia** [comment] 2017-02-07 20:53
Hi,
Actually remove that check is not enough, because in the ASP.NET controller that creates the request to provision the site we still check to have a valid email address for the user, because we use it to reference the user and to do the EnsureUser, in case of need. So, you can change the behavior, in order to avoid having the need of an email address, but it is not that easy. You will have to change also the Controller and the JobHandler.

**Comment by joelfmrodrigues** [comment] 2017-02-07 21:37
Thanks... I've checked the code and realise that straight away. I was thinking on a different approach: maybe we could query the infrastructural site to get the user information if the previous query fails?

**Comment by PaoloPia** [comment] 2017-02-08 11:22
Hi,
Can you expand a little bit more on this idea? What would you like to query for in the Infrastructural Site Collection? Do you mean searching for a "default" Site Collection Administrator or something like that? Thanks.

**Comment by leedale1981** [comment] 2017-02-08 13:16
So I've got another idea that I have tested in my environment and I could see working for most users. If in fact there is no email set due to the user only having a SharePoint P1 licence or something we can set their email to the userPrincipalName which in Office 365 would be an email address. This is presumably how we are able to add all Office 365 users as site collection admins through the OOTB UI?

I could submit a PR that essentially updates the method below:

`private async Task<PrincipalsViewModel> MapUsers(IGraphServiceUsersCollectionPage source)
        {
            PrincipalsViewModel result = new PrincipalsViewModel();

            if (source != null)
            {
                foreach (var u in source)
                {
                    u.Mail = (string.IsNullOrEmpty(u.Mail)) ? u.UserPrincipalName : u.Mail;
                    result.Principals.Add(await MapUser(u));
                }
            }

            return result;
        }`

**Comment by PaoloPia** [comment] 2017-02-08 13:26
Ok! That's a great idea! Feel free to implement the PR and to submit it after proper testing. Thank you.

**Comment by joelfmrodrigues** [comment] 2017-02-08 17:13
@PaoloPia  Yes I was talking about something like that, basically to allow us to resolve a different user and be able to use the engine on Dev environments where users have no email.
Although, @leedale1981  has an approach that looks better 👍 I will also give it a try tomorrow so I can at least help testing

**Comment by joelfmrodrigues** [comment] 2017-02-09 08:49
I can't get this to work @leedale1981

**Comment by leedale1981** [comment] 2017-02-09 08:52
Do you mean my PR or the general approach? I've tested on my environment with both users that have just SharePoint licences (therefore no email address) and users that have E1 licences. In the case of users with no emails it reverts back to using the UserPrincipleName for the user.

**Comment by joelfmrodrigues** [comment] 2017-02-09 08:59
Your PR. I've applied the same change to my project. The approach makes perfect sense to me, but it looks like I keep getting the same error which is really strange...

**Comment by leedale1981** [comment] 2017-02-09 09:12
Have you managed to attach a debugger and see whether the UserPrincipleName has a value?

**Comment by joelfmrodrigues** [comment] 2017-02-09 09:15
No, that's the next step I need to try, but unfortunately I can only try again tomorrow or later today (doing this out of work hours)

**Comment by PaoloPia** [comment] 2017-02-09 09:47
The submitted PR looks good to me, and I'm going to merge it. Thanks @leedale1981 for your efforts!

**Comment by joelfmrodrigues** [comment] 2017-02-10 09:23
In my scenario the error seems to be caused by something else. Yesterday, one of my colleagues that manages the dev environment updated it to E3 and my dev account now has and email associated, although, I keep getting the same error. I will re-deploy the provisioning engine and try again when I find some spare time and let you know in case the error persists.

**Comment by PaoloPia** [comment] 2017-02-24 15:55
Hi,
eventually you can try the new setup wizard that we released in preview under the DEV branch just a couple of days ago. In the meantime I will close this item, because PR #223 solved the issue.

**Closed by PaoloPia** 2017-02-24 15:55 UTC
