### ISSUE TITLE
The selection of sub site templates does not work

### ISSUE THREAD

**Issue by sogrjp** [SharePoint/PnP-Partner-Pack#234] opened 2017-02-22 10:42 UTC
The selection of sub site templates does not work when you create a sub site.
I change provider sub site templates and always load the same (Empty Sub Site Template). It does not load any of the ones I've created.
It only works when you are creating a Site Collection.
I need for my customer, to be able to select sub site templates for the creation of sub sites.
Could you help me with this?

**Comment by PaoloPia** [comment] 2017-02-24 15:59
Hi,
Thanks for using the PnP Partner Pack. How do you save your templates?

**Comment by sogrjp** [comment] 2017-02-27 07:15
Hello Paolo, thank you very much for assisting me.
I have seen that the Template loading only works when you use Search criteria control, but when you change the selected Templates provider, the templates it displays are not updated.
It does not work to create a sub site from a template, the error reporting is as follows:
<The Provisioning Template URI template.xml is not valid.>
The used template has been saved using the Save as provisioning Template feature (Global Tenant / Site Collection)

**Comment by PaoloPia** [comment] 2017-03-12 08:53
Hi,
I'm sorry but I cannot reproduce the issue. Could you please provide me a step by step guidance about how to reproduce the issue? Thanks.

**Comment by PaoloPia** [comment] 2017-04-10 19:57
Hi,
Do you have any new feedback about this issue? Or can I assume that you solved it and close this item? Thanks.

**Comment by PaoloPia** [comment] 2017-04-14 10:56
Hi, 
Due to no answer I will close this item. In case of any further issue, feel free to let me know and I will be more than happy to open this item again. Thanks.

**Closed by PaoloPia** 2017-04-14 10:56 UTC
Labels: waiting-for-clarification
