### ISSUE TITLE
InnerException during site creation in Azure (You cannot call a method on a null-valued expression.)

### ISSUE THREAD

**Issue by pitsta** [SharePoint/PnP-Partner-Pack#243] opened 2017-03-14 20:53 UTC
Hi there,
I have had an error that has not allowed me to continue. I have provided some screenshots and stack trace below. This I have tried approx 6 times and always the same conclusion.

UPDATE: see linked file.
[https://1drv.ms/b/s!Au9fSRc7sAg2i2rO86YkD3W7QhsT](https://1drv.ms/b/s!Au9fSRc7sAg2i2rO86YkD3W7QhsT)

Let me know if you need more information. Thank you.

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at OfficeDevPnP.PartnerPack.Setup.ViewModel.MainViewModel.<Setup>b__146_0() in C:\Users\ShaunPitt\Documents\GitHub\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Setup\ViewModel\MainViewModel.cs:line 450
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.Runspaces.Pipeline.Invoke()
   at OfficeDevPnP.PartnerPack.Setup.Components.Run.RunScript(String powershellpath, Hashtable Parameters) in C:\Users\ShaunPitt\Documents\GitHub\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Setup\Components\Run.cs:line 56
   at OfficeDevPnP.PartnerPack.Setup.Components.SetupManager.<BuildAndDeployWebSite>d__18.MoveNext() in C:\Users\ShaunPitt\Documents\GitHub\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Setup\Components\SetupManager.cs:line 711
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OfficeDevPnP.PartnerPack.Setup.Components.SetupManager.<SetupPartnerPackAsync>d__1.MoveNext() in C:\Users\ShaunPitt\Documents\GitHub\PnP-Partner-Pack\OfficeDevPnP.PartnerPack.SiteProvisioning\OfficeDevPnP.PartnerPack.Setup\Components\SetupManager.cs:line 103

kind regards
Shaun

**Comment by PaoloPia** [comment] 2017-03-17 13:35
Hi,
Thanks for using PnP Partner Pack. Looks like the issue is related to the execution of the PowerShell script that builds and publish the Azure Web Site. Can you show me the Message of the InnerException of the AggregateException that you get? I'm interested in the message like "You cannot call ..." Or can you simply run the app without the debugger and showing me the error message that will pop up in the error box? Thanks.

**Comment by PaoloPia** [comment] 2017-04-10 19:57
Hi,
Do you have any new feedback about this issue? Or can I assume that you solved it and close this item? Thanks.

**Comment by pitsta** [comment] 2017-04-11 10:53
Hi there Paolo

Apologies I've been on another project. I will check my notes later in the week and give you my feedback.
Thanks again for the amazing work you and your team are doing.

Regards
Shaun Pitt

Sent from my iPhone

On 11 Apr 2017, at 5:58 am, Paolo Pialorsi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
Do you have any new feedback about this issue? Or can I assume that you solved it and close this item? Thanks.

**Comment by pitsta** [comment] 2017-04-24 01:08
Hi Paolo,

there are two Inner Exceptions that occur on the SetupManager.SetupPartnerPackAsync(MapSetupInformation(this)).Wait() function:

1: CmdletInvocationException: You cannot call a method on a null-valued expression.
{You cannot call a method on a null-valued expression.}

and second is same.
2: RuntimeException: You cannot call a method on a null-valued expression.
{"You cannot call a method on a null-valued expression."}

Hope this helps

kind regards
Shaun

**Comment by PaoloPia** [comment] 2017-05-07 09:27
Hi Shaun,
we found a bug in the setup wizard, when it was used within VS2017. It looks like your issue falls into this category. We already fixed the issue, so can you try again? In the meantime I will close this item, but in case of any further issue, please let me know and I will be more than happy to re-open this item and support you. Thanks.

**Closed by PaoloPia** 2017-05-07 09:27 UTC
Labels: waiting-for-clarification

**Comment by johnbrice** [comment] 2017-10-10 07:40
Still experiencing this issue with VS17
